[main]
font=Inter:weight=Medium:size=13
icons-enabled=yes
terminal=kitty --
prompt="   "

# Forzar ejecución nativa para saltarse el wrapper de Lua que crashea
launch-prefix=setsid -f

# Dimensiones y espaciado
lines=8
width=45
horizontal-pad=25
vertical-pad=20
inner-pad=10
line-height=26

[colors]
background=1e1e2ef2
text=cdd6f4ff
match=89b4faff
selection=89b4faff
selection-text=1e1e2eff
selection-match=5f2f63ff
border=89b4faff

[border]
width=2
radius=16

